Initializing SE-ResNet model training...
Loading WaveFake dataset...
training_dataset size: 73360
validation_dataset size: 9170
test_dataset size: 9170
Set up the SE-ResNet model...
Training started...
Training batches: 100%|█████████████████████████████████████████████████████████████████████████████████████| 287/287 [00:37<00:00,  7.64it/s]
Validation batches: 100%|█████████████████████████████████████████████████████████████████████████████████████| 36/36 [00:05<00:00,  6.89it/s]
Training batches:   6%|████▊                                                                                 | 16/287 [00:02<00:49,  5.49it/s]

New best model found! Saving...
Epoch: 1
Training_Loss: 1.0494565611724653
Validating_Loss: 0.4585612532165315
Training_Accuracy: 0.6152671575546265
Validating_Accuracy: 0.8273718357086182
Training_F1_Score: 0.597988486289978
Validating_F1_Score: 0.8038693070411682
Training_Precision: 0.6625243425369263
Validating_Precision: 0.8306124210357666
Training_Recall: 0.6152671575546265
Validating_Recall: 0.8273718357086182
Training_AUROC: 0.9304852485656738
Validating_AUROC: 0.9755619764328003
Training Epochs:   1%|▊                                                                                     | 1/100 [00:45<1:15:33, 45.79s/it]
Traceback (most recent call last):
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/src/training/train_model.py", line 200, in <module>
    for waveform, label in tqdm(train_loader, desc="Training batches"):
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/anaconda3/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/opt/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 54, in _pin_memory_loop
    do_one_step()
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 31, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/anaconda3/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/hessos4l/Downloads/DetectingVocoderFingerprints/myenv/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 355, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/anaconda3/lib/python3.9/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/anaconda3/lib/python3.9/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/anaconda3/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/opt/anaconda3/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
